[package]

version = "0.2.0"

# Description
category = "isaaclab"
readme  = "README.md"

title = "Zbot Template"
author = "crowznl"
maintainer = "crowznl"
description="Zbot Template for Isaac Lab"
repository = "https://github.com/crowznl/IsaacLabExtensionTemplate.git"
keywords = ["extension", "Zbot", "isaaclab"]

[dependencies]
"omni.isaac.lab" = {}
"omni.isaac.lab_assets" = {}
"omni.isaac.lab_tasks" = {}
# NOTE: Add additional dependencies here

[[python.module]]
name = "Zbot"

[isaaclab_settings]
# TODO: Uncomment and list any apt dependencies here.
#       If none, leave it commented out.
# apt_deps = ["example_package"]
# TODO: Uncomment and provide path to a ros_ws
#       with rosdeps to be installed. If none,
#       leave it commented out.
# ros_ws = "path/from/extension_root/to/ros_ws"
